// This file was auto-generated by edlcodegen.exe
// Changes to this file may be lost if the file is regenerated.

#pragma once
#include <VbsEnclaveABI\Host\HostHelpers.h>
#include "DeveloperTypes.h"

namespace CodeGenTest
{
    namespace Untrusted::Implementation
    {
        using namespace CodeGenTest::DeveloperTypes;
        
        HRESULT TestFunc(_In_  bool arg1, _In_ const uint32_t* arg2, _Inout_  int32_t* arg3, _Out_  std::unique_ptr<uint64_t>& arg4, _Inout_  StructWithPointers& arg5, _Out_  std::unique_ptr<StructWithPointers>& arg6, _Inout_  std::vector<StructWithPointers>& arg7, _Out_  std::vector<std::int16_t>& arg8, _Out_  std::array<std::wstring, 2>& arg9);

    };
}
