// This file was auto-generated by edlcodegen.exe
// Changes to this file may be lost if the file is regenerated.

#pragma once

namespace CodeGenTest
{
    namespace VTL1_Stubs
    {
        void* TestFunc0_Generated_Stub(void* function_context);
        void* __AbiRegisterVtl0Callbacks_CodeGenTest__(void* function_context);

    }
}
