// This file was auto-generated by edlcodegen.exe
// Changes to this file may be lost if the file is regenerated.

#pragma once
#include <VbsEnclaveABI\Shared\VbsEnclaveAbiBase.h>
#include "vbsenclave_flatbuffer_support_generated.h"
#include <VbsEnclaveABI\Shared\ConversionHelpers.h>

namespace CodeGenTest::DeveloperTypes
{

struct TestStruct1;

struct NestedStructWithPointers;

struct StructWithPointers;

struct TestStruct1
{
    std::int64_t int64_val {};
    std::uint64_t uint64_val {};
    std::array<std::int64_t, 5> array1 {};
};

struct NestedStructWithPointers
{
    std::unique_ptr<int32_t> int32_ptr {};
    std::unique_ptr<TestStruct1> struct_ptr {};
};

struct StructWithPointers
{
    std::unique_ptr<NestedStructWithPointers> nested_struct_ptr {};
};

struct TestFunc_0_args
{
    HRESULT m__return_value_ {};
    bool m_arg1 {};
    std::unique_ptr<uint32_t> m_arg2 {};
    std::unique_ptr<int32_t> m_arg3 {};
    std::unique_ptr<uint64_t> m_arg4 {};
    StructWithPointers m_arg5 {};
    std::unique_ptr<StructWithPointers> m_arg6 {};
    std::vector<StructWithPointers> m_arg7 {};
    std::vector<std::int16_t> m_arg8 {};
    std::array<std::wstring, 2> m_arg9 {};
};

struct TestFunc_1_args
{
    HRESULT m__return_value_ {};
    bool m_arg1 {};
    std::unique_ptr<uint32_t> m_arg2 {};
    std::unique_ptr<int32_t> m_arg3 {};
    std::unique_ptr<uint64_t> m_arg4 {};
    StructWithPointers m_arg5 {};
    std::unique_ptr<StructWithPointers> m_arg6 {};
    std::vector<StructWithPointers> m_arg7 {};
    std::vector<std::int16_t> m_arg8 {};
    std::array<std::wstring, 2> m_arg9 {};
};

}

// Struct metadata
namespace VbsEnclaveABI::Shared::Converters
{

template <>
struct StructMetadata<CodeGenTest::DeveloperTypes::TestStruct1>
{
    static constexpr auto members = std::make_tuple(&CodeGenTest::DeveloperTypes::TestStruct1::int64_val,&CodeGenTest::DeveloperTypes::TestStruct1::uint64_val,&CodeGenTest::DeveloperTypes::TestStruct1::array1);
};

template <>
struct StructMetadata<CodeGenTest::FlatbuffersDevTypes::TestStruct1T>
{
    static constexpr auto members = std::make_tuple(&CodeGenTest::FlatbuffersDevTypes::TestStruct1T::int64_val,&CodeGenTest::FlatbuffersDevTypes::TestStruct1T::uint64_val,&CodeGenTest::FlatbuffersDevTypes::TestStruct1T::array1);
};

template <>
struct StructMetadata<CodeGenTest::DeveloperTypes::NestedStructWithPointers>
{
    static constexpr auto members = std::make_tuple(&CodeGenTest::DeveloperTypes::NestedStructWithPointers::int32_ptr,&CodeGenTest::DeveloperTypes::NestedStructWithPointers::struct_ptr);
};

template <>
struct StructMetadata<CodeGenTest::FlatbuffersDevTypes::NestedStructWithPointersT>
{
    static constexpr auto members = std::make_tuple(&CodeGenTest::FlatbuffersDevTypes::NestedStructWithPointersT::int32_ptr,&CodeGenTest::FlatbuffersDevTypes::NestedStructWithPointersT::struct_ptr);
};

template <>
struct StructMetadata<CodeGenTest::DeveloperTypes::StructWithPointers>
{
    static constexpr auto members = std::make_tuple(&CodeGenTest::DeveloperTypes::StructWithPointers::nested_struct_ptr);
};

template <>
struct StructMetadata<CodeGenTest::FlatbuffersDevTypes::StructWithPointersT>
{
    static constexpr auto members = std::make_tuple(&CodeGenTest::FlatbuffersDevTypes::StructWithPointersT::nested_struct_ptr);
};

template <>
struct StructMetadata<CodeGenTest::DeveloperTypes::TestFunc_0_args>
{
    static constexpr auto members = std::make_tuple(&CodeGenTest::DeveloperTypes::TestFunc_0_args::m__return_value_,&CodeGenTest::DeveloperTypes::TestFunc_0_args::m_arg1,&CodeGenTest::DeveloperTypes::TestFunc_0_args::m_arg2,&CodeGenTest::DeveloperTypes::TestFunc_0_args::m_arg3,&CodeGenTest::DeveloperTypes::TestFunc_0_args::m_arg4,&CodeGenTest::DeveloperTypes::TestFunc_0_args::m_arg5,&CodeGenTest::DeveloperTypes::TestFunc_0_args::m_arg6,&CodeGenTest::DeveloperTypes::TestFunc_0_args::m_arg7,&CodeGenTest::DeveloperTypes::TestFunc_0_args::m_arg8,&CodeGenTest::DeveloperTypes::TestFunc_0_args::m_arg9);
};

template <>
struct StructMetadata<CodeGenTest::FlatbuffersDevTypes::TestFunc_0_argsT>
{
    static constexpr auto members = std::make_tuple(&CodeGenTest::FlatbuffersDevTypes::TestFunc_0_argsT::m__return_value_,&CodeGenTest::FlatbuffersDevTypes::TestFunc_0_argsT::m_arg1,&CodeGenTest::FlatbuffersDevTypes::TestFunc_0_argsT::m_arg2,&CodeGenTest::FlatbuffersDevTypes::TestFunc_0_argsT::m_arg3,&CodeGenTest::FlatbuffersDevTypes::TestFunc_0_argsT::m_arg4,&CodeGenTest::FlatbuffersDevTypes::TestFunc_0_argsT::m_arg5,&CodeGenTest::FlatbuffersDevTypes::TestFunc_0_argsT::m_arg6,&CodeGenTest::FlatbuffersDevTypes::TestFunc_0_argsT::m_arg7,&CodeGenTest::FlatbuffersDevTypes::TestFunc_0_argsT::m_arg8,&CodeGenTest::FlatbuffersDevTypes::TestFunc_0_argsT::m_arg9);
};

template <>
struct StructMetadata<CodeGenTest::DeveloperTypes::TestFunc_1_args>
{
    static constexpr auto members = std::make_tuple(&CodeGenTest::DeveloperTypes::TestFunc_1_args::m__return_value_,&CodeGenTest::DeveloperTypes::TestFunc_1_args::m_arg1,&CodeGenTest::DeveloperTypes::TestFunc_1_args::m_arg2,&CodeGenTest::DeveloperTypes::TestFunc_1_args::m_arg3,&CodeGenTest::DeveloperTypes::TestFunc_1_args::m_arg4,&CodeGenTest::DeveloperTypes::TestFunc_1_args::m_arg5,&CodeGenTest::DeveloperTypes::TestFunc_1_args::m_arg6,&CodeGenTest::DeveloperTypes::TestFunc_1_args::m_arg7,&CodeGenTest::DeveloperTypes::TestFunc_1_args::m_arg8,&CodeGenTest::DeveloperTypes::TestFunc_1_args::m_arg9);
};

template <>
struct StructMetadata<CodeGenTest::FlatbuffersDevTypes::TestFunc_1_argsT>
{
    static constexpr auto members = std::make_tuple(&CodeGenTest::FlatbuffersDevTypes::TestFunc_1_argsT::m__return_value_,&CodeGenTest::FlatbuffersDevTypes::TestFunc_1_argsT::m_arg1,&CodeGenTest::FlatbuffersDevTypes::TestFunc_1_argsT::m_arg2,&CodeGenTest::FlatbuffersDevTypes::TestFunc_1_argsT::m_arg3,&CodeGenTest::FlatbuffersDevTypes::TestFunc_1_argsT::m_arg4,&CodeGenTest::FlatbuffersDevTypes::TestFunc_1_argsT::m_arg5,&CodeGenTest::FlatbuffersDevTypes::TestFunc_1_argsT::m_arg6,&CodeGenTest::FlatbuffersDevTypes::TestFunc_1_argsT::m_arg7,&CodeGenTest::FlatbuffersDevTypes::TestFunc_1_argsT::m_arg8,&CodeGenTest::FlatbuffersDevTypes::TestFunc_1_argsT::m_arg9);
};

}
